added commit hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,24 +1,23 @@
-#!/bin/bash
-
-HAS_ISSUES=0
-FIRST_FILE=1
-
-for file in $(git diff --name-only --staged); do
-    FMT_RESULT="$(rustfmt --skip-children --force --write-mode diff $file 2>/dev/null || true)"
-    if [ "$FMT_RESULT" != "" ]; then
-        if [ $FIRST_FILE -eq 0 ]; then
-            echo -n ", "
-        fi  
-        echo -n "$file"
-        HAS_ISSUES=1
-        FIRST_FILE=0
+#!/bin/bash -e
+declare -a rust_files=()
+files=$(git diff-index --name-only HEAD)
+echo 'Formatting source files'
+for file in $files; do
+    if [ ! -f "${file}" ]; then
+        continue
+    fi
+    if [[ "${file}" == *.rs ]]; then
+        rust_files+=("${file}")
     fi
 done
-
-if [ $HAS_ISSUES -eq 0 ]; then
-    exit 0
+if [ ${#rust_files[@]} -ne 0 ]; then
+    command -v rustfmt >/dev/null 2>&1 || { echo >&2 "Rustfmt is required but it's not installed. Aborting."; exit 1; }
+    $(command -v rustfmt) ${rust_files[@]} &
 fi
-
-echo ". Your code has formatting issues in files listed above. Format your code with \`make format\` or call rustfmt 
-manually."
-exit 1
+wait
+if [ ${#rust_files[@]} -ne 0 ]; then
+    git add ${rust_files[@]}
+    echo "Formatting done, changed files: ${rust_files[@]}"
+else
+    echo "No changes, formatting skipped"
+fi
